### ISSUE TITLE
May I ask which item rv leaves of the third-party package is? Thank you

### ISSUE THREAD

**Issue by jayden-leo** [suddrey-qut/lingua_packages#2]
May I ask which item “rv_leaves” of the third-party package is? Thank you

**Comment by suddrey-qut** [comment]
You can find the URLs to each submodule in the .gitmodules file located here: https://github.com/suddrey-qut/lingua_packages/blob/master/.gitmodules

The submodules are not linked correctly in GitHub due to the indicated repositories being hosted on BitBucket.
